### ISSUE TITLE
Decimal128 validation bug

### ISSUE THREAD

**Issue by johndugan** [BoLaMN/ajv-bsontype#3]
Hi There,

I have an order total stored as a number in JavaScript that I am _successfully_ converting and inserted as a Decimal128 type per MongoDB's guidance on [modeling monetary data](https://docs.mongodb.com/manual/tutorial/model-monetary-data/index.html#numeric-decimal).

However, once I add the `'decimal'` validation, the insertion fails with a 400 error saying:
```
[
  {
    "keyword": "bsonType",
    "params": {
      "bsonType": "decimal"
    },
    "message": "should be decimal got 3",
    "dataPath": ".total",
    "schemaPath": "#/properties/total/bsonType"
  }
]
```
If I comment out the `total` validation, the request succeeds, and the `total` value is properly inserted in to MongoDB with as the expected Decimal128 type (see screenshot). Below is my request and validator setup.

**REQUEST**
```
{"total": 3}
```

**VALIDATOR**
```
import Ajv from 'ajv';
import bson from 'ajv-bsontype';
import {Decimal128} from 'mongodb';

// Create new validator
const ajv = new Ajv({allErrors: true, useDefaults: true});

// Add bson validation to validator
bson(ajv);

const schema = {
    required: ['status', 'total'],
    properties: {
        status: {
            bsonType: 'string',
            enum: ['pending', 'complete'],
            default: 'pending',
            description: 'must be a String'
        },
        total: {
            bsonType: 'decimal',
            description: 'must be a decimal'
        }
    },
    additionalProperties: true
};

export function transpile(order) {
    // convert property values to their to mongo schema requirement
    order.total = Decimal128.fromString(order.total.toString());
    return order;
}

export const validator = ajv.compile(schema);
```
![decimal](https://user-images.githubusercontent.com/1389303/57961005-c4659380-78d1-11e9-9a9e-a9c0d66f22f4.png)

**Comment by matthew1534** [comment]
I can confirm this issue exists (another repo that uses ajv-bsontype): https://github.com/devetry/mongo-schemer/issues/9

**Comment by matthew1534** [comment]
Raised a PR to fix this issue: https://github.com/BoLaMN/ajv-bsontype/pull/4

**Comment by johndugan** [comment]
@matthew1534 added a PR to your fork. There were several more issues to resolve.
